services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: rails_app_development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails-app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rails_app_development
    working_dir: /rails-app
    tty: true
    stdin_open: true
volumes:
  postgres_data:
