default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: rails_app_development

test:
  <<: *default
  database: rails_app_test
#
production:
  primary: &primary_production
    <<: *default
    database: rails_app_production
    username: rails_app
    password: <%= ENV["RAILS_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_app_production_queue
    migrations_paths: db/queue_migrate
